name: DEPLOY
on:
  push:
    branches: [ master ]
    paths:
      - 'version.txt'
  pull_request:
    branches: [ master ]
    paths:
      - 'version.txt'
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: |
        msbuild /t:Restore /p:Configuration=Release
        msbuild /m /p:Configuration=Release
        cd ./Gevjon-Core/bin/Release
        7z a Gevjon.7z *
        cd ../../../
        Remove-Item public -Recurse -ErrorAction Ignore
        mkdir public
        mv ./Gevjon-Core/bin/Release/Gevjon.7z ./public/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Gevjon
        retention-days: 1
        path: |
          public/Gevjon.7z
 
  release:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:      
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: Gevjon
        path: public
    - name: Pack
      run: |
        mkdir -p ./pack
        mv ./public/Gevjon.7z ./pack/
        cd ./pack
        7z x Gevjon.7z
        rm Gevjon.7z -f
        wget -q -O - https://ygocdb.com/api/v0/cards.zip | gunzip - > ./cards.json
        wget -q -O ./cards.ver https://ygocdb.com/api/v0/cards.zip.md5
        7z a Gevjon.7z *
        cd ..
        mv ./pack/version.txt ./public/
        mv ./pack/Gevjon.7z ./public/
        VER=$(head -n 1 ./public/version.txt)
        echo "TAG_NAME=$VER" >> $GITHUB_ENV
        CONTENT="Checksum(SHA256): "$(sha256sum public//Gevjon.7z | awk '{print $1}')
        echo "DEFAULT_CONTENT=$CONTENT" >> $GITHUB_ENV
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ env.DEFAULT_CONTENT }}
        generate_release_notes: true
        tag_name: ${{ env.TAG_NAME }}
        files: public/Gevjon.7z

    - name: Deploy github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        keep_files: true
        
    - name: Purge CDN cache
      if: github.ref == 'refs/heads/master'
      run: |
        curl https://purge.jsdelivr.net/gh/RyoLee/Gevjon@gh-pages/version.txt
        curl https://purge.jsdelivr.net/gh/RyoLee/Gevjon@gh-pages/Gevjon.7z