name: CI
on:
  push:
    branches: [ master ]
    paths:
      - 'Core/Properties/AssemblyInfo.cs'
  pull_request:
    branches: [ master ]
    paths:
      - 'Core/Properties/AssemblyInfo.cs'
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: |
        Remove-Item public -Recurse -ErrorAction Ignore
        mkdir public
        msbuild /t:Restore /p:Configuration=Release
        msbuild /m /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None
        cp ./README.md ./Core/bin/Release/net6.0-windows/
        cd ./Core/bin/Release/net6.0-windows
        (get-item Gevjon.exe).VersionInfo.ProductVersion > ../../../public/version.txt
        7z a Gevjon.7z *
        mv ./Gevjon.7z ../../../public/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Gevjon
        retention-days: 1
        path: |
          public/Gevjon.7z
          public/version.txt

  release:
    needs: build
    if: ${{github.event_name != 'workflow_dispatch' && github.ref == 'refs/heads/master'}}
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: Gevjon
        path: public
    - name: Init
      run: |
        VER=$(head -n 1 ./public/version.txt)
        echo "TAG_NAME=$VER" >> $GITHUB_ENV
        CONTENT="Checksum(SHA256): "$(sha256sum public//Gevjon.7z | awk '{print $1}')
        echo "DEFAULT_CONTENT=$CONTENT" >> $GITHUB_ENV
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ env.DEFAULT_CONTENT }}
        generate_release_notes: true
        tag_name: ${{ env.TAG_NAME }}
        files: public/Gevjon.7z

    - name: Deploy github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        keep_files: true
