name: Deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'version.txt'
  pull_request:
    branches: [ master ]
    paths:
      - 'version.txt'

jobs:

  build:
    if: github.ref == 'refs/heads/master'
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: |
        msbuild /t:Restore /p:Configuration=Release
        msbuild /m /p:Configuration=Release
        cd ./Gevjon-Core/bin/Release
        7z a Gevjon.7z *
        cd ../../../
        Remove-Item public -Recurse -ErrorAction Ignore
        mkdir public
        cp -f version.txt ./public/
        mv ./Gevjon-Core/bin/Release/Gevjon.7z ./public/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: |
          public/Gevjon.7z
          public/version.txt

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        keep_files: true
 
  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:      
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: output
        path: |
          public/Gevjon.7z
          version.txt
    - name: Set Version
      run: |
        VER=$(head -n 1 version.txt)
        echo "TAG_NAME=$VER" >> $GITHUB_ENV
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        files: public/Gevjon.7z
    - name: Purge CDN cache
      if: github.ref == 'refs/heads/master'
      run: |
        curl https://purge.jsdelivr.net/gh/RyoLee/Gevjon@gh-pages/version.txt
        curl https://purge.jsdelivr.net/gh/RyoLee/Gevjon@gh-pages/Gevjon.7z
