name: .NET Core Desktop

on:
  push:
    branches: [ master , dev ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Build Master
      if: github.ref == 'refs/heads/master'
      run: |
        msbuild /t:Restore /p:Configuration=Release /p:Platform=x86
        msbuild /m /p:Configuration=Release /p:Platform=x86
        cd ./Gevjon-Core/bin/Release
        7z a Gevjon.7z *
        cd ../../../
        Remove-Item public -Recurse -ErrorAction Ignore
        mkdir public
        mv ./Gevjon-Core/bin/Release/Gevjon.7z ./public/
              
    - name: Build Develop
      if: github.ref == 'refs/heads/dev'
      run: |
        msbuild /t:Restore /p:Configuration=Release /p:Platform=x86
        msbuild /m /p:Configuration=Release /p:Platform=x86
        cd ./Gevjon-Core/bin/Release
        7z a Gevjon-dev.7z *
        cd ../../../
        Remove-Item public -Recurse -ErrorAction Ignore
        mkdir public
        mv ./Gevjon-Core/bin/Release/Gevjon-dev.7z ./public/
      
    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        keep_files: true